apiVersion: v1
kind: Pod
metadata:
  name: authentication-client-pod
spec:
  containers:
    - name: authentication-client
      image: pavelnenov/spring-is-here-authentication-client
      readinessProbe:
        httpGet:
          path: /ping
          port: 8080
